
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${THIA_DB_PASSWORD}
    volumes:
      - ${DB_VOLUME:-postgres_data}:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-6543}:5432"
    networks:
      - ${NETWORK_NAME:-thia_net}

  redis:
    image: redis:7
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - ${NETWORK_NAME:-thia_net}

  web:
    shm_size: '2gb' 
    build:
      context: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
      - ${STATIC_VOLUME:-static_volume}:/app/staticfiles
      - ./media:/app/media
      - ./docker_media/videos:/app/media/videos
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - db
      - redis
    ports:
      - "${WEB_PORT:-8000}:8000"
    networks:
      - ${NETWORK_NAME:-thia_net}

  celery:
    build: .
    command: celery -A thia worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - ${ENV_FILE:-.env}
    user: celeryuser
    networks:
      - ${NETWORK_NAME:-thia_net}

  celery-beat:
    build: .
    command: celery -A thia beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - ${ENV_FILE:-.env}
    user: celeryuser
    networks:
      - ${NETWORK_NAME:-thia_net}

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - .:/app
      - ${STATIC_VOLUME:-static_volume}:/app/staticfiles
      - ./media:/app/media
      - ./docker_media/videos:/app/media/videos
    depends_on:
      - web
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - ${NETWORK_NAME:-thia_net}

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  thia_net:
    driver: bridge
