
services:
  db:
    image: postgres:15
    env_file:
      - .env.test
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${THIA_DB_PASSWORD}
    ports:
      - "6545:5432"  # Avoid conflict with dev (6544), prod (6546)
    networks:
      - thia_net_test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  web:
    env_file:
      - .env.test
    build:
      context: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
      - static_volume_test:/app/staticfiles
      - ./media:/app/media
      - ./docker_media/videos:/app/media/videos
    ports:
      - "8002:8000"  # Web app port (unique)
    depends_on:
      - db
      - redis
    networks:
      - thia_net_test

  celery:
    build: .
    command: celery -A thia worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.test
    depends_on:
      - db
      - redis
    user: celeryuser
    networks:
      - thia_net_test

  celery-beat:
    build: .
    command: celery -A thia beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.test
    depends_on:
      - db
      - redis
    user: celeryuser
    networks:
      - thia_net_test

  redis:
    env_file:
      - .env.test
    image: redis:7
    ports:
      - "6380:6379"  # Avoid conflict with other Redis
    networks:
      - thia_net_test

  nginx:
    image: nginx:alpine
    ports:
      - "8082:80"    # Avoid conflict with other nginx containers
      - "4442:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - .:/app
      - static_volume_test:/app/staticfiles
      - ./media:/app/media
      - ./docker_media/videos:/app/media/videos
    depends_on:
      - web
    env_file:
      - .env.test
    networks:
      - thia_net_test

volumes:
  postgres_data_test:
  static_volume_test:

networks:
  thia_net_test:
    driver: bridge


